### ISSUE TITLE
ARM Macs support

### ISSUE THREAD

**Issue by Dolfost** [BerntA/BrainBread2#4]
When there will be Apple silicon game support? I have played this game for 70 hours on my linux pc, but I lost access to my pc, and stuck with a MacBook Air M2. The game is 32bit or something, and steam wont launch it... Will there be a native Mac ARM port?

**Comment by BerntA** [comment]
Sadly not, we do not have engine access, nor does Valve have any intention to build SDK 2013 for 64-bit:: 🤷‍♂️

**Comment by Dolfost** [comment]
> Sadly not, we do not have engine access, nor does Valve have any intention to build SDK 2013 for 64-bit:: 🤷‍♂️

That's sad. Thank You for information.
